export interface Product {
  id: string
  brand: string
  name: string
  blurb: string
  size?: string
  rating: number
  reviews: number
  badge?: string
  image: string
  url: string
}

export interface Collection {
  id: string
  eyebrow: string
  title: string
  subtitle: string
  hook: string
  image: string
  products: Product[]
}

const AMZ = (path: string) => `https://www.amazon.com${path}?tag=santoglam-20`

export const collections: Collection[] = [
  {
    id: "hotel",
    eyebrow: "Collection 01",
    title: "The Hotel Room Edit",
    subtitle: "The robe, the scent, the thread count.",
    hook: "Recreate the exact feeling of a five-star suite, for a fraction of the cost of one night in one.",
    image:
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=1400&q=80&auto=format&fit=crop",
    products: [
      {
        id: "marriott-robe",
        brand: "Marriott Hotels",
        name: "Waffle Shawl Robe",
        blurb: "300-thread cotton waffle. The one you keep stealing at check-out — now yours to keep.",
        rating: 4.8,
        reviews: 2140,
        badge: "Bestseller",
        image: "https://m.media-amazon.com/images/I/61AwtNPq0fL._SL1200_.jpg",
        url: AMZ("/dp/B09JCPHJHY/"),
      },
      {
        id: "slip-pillowcase",
        brand: "Slip",
        name: "Pure Silk Queen Pillowcase",
        blurb: "Mulberry silk that keeps skin and hair happy while you sleep. The single upgrade guests always ask about.",
        rating: 4.7,
        reviews: 8760,
        badge: "Editor's Pick",
        image: "https://m.media-amazon.com/images/I/51nY1o-bp5L._SL1200_.jpg",
        url: AMZ("/dp/B01JZVYD6G/"),
      },
      {
        id: "slip-mask",
        brand: "Slip",
        name: "Silk Sleep Mask",
        blurb: "Everything else goes dark. The reason hotel sleep hits different.",
        rating: 4.7,
        reviews: 5310,
        image: "https://m.media-amazon.com/images/I/61nnof-zqAL._SL1200_.jpg",
        url: AMZ("/dp/B01JZX0Y3A/"),
      },
      {
        id: "margiela-lazy-sunday",
        brand: "Maison Margiela",
        name: "REPLICA — Lazy Sunday Morning",
        blurb: "The exact scent of a good hotel bed, bottled.",
        size: "3.4 oz Eau de Toilette",
        rating: 4.6,
        reviews: 3980,
        image: "https://m.media-amazon.com/images/I/71pGwqDYgPL._SL1200_.jpg",
        url: AMZ("/dp/B00JXMUR2W/"),
      },
      {
        id: "diptyque-baies",
        brand: "Diptyque",
        name: "Baies Candle",
        blurb: "Blackcurrant & rose. The candle that makes people ask 'what is that smell.'",
        size: "6.5 oz",
        rating: 4.8,
        reviews: 6210,
        badge: "Trending",
        image: "https://m.media-amazon.com/images/I/41hlvTT0-KL._SL1200_.jpg",
        url: AMZ("/dp/B00429KMH6/"),
      },
      {
        id: "nest-votive",
        brand: "NEST New York",
        name: "Bamboo Votive",
        blurb: "The small flame beside the bed. Cheap enough to buy on impulse, good enough to become a habit.",
        rating: 4.7,
        reviews: 1870,
        image: "https://m.media-amazon.com/images/I/41lCeJ3nhsL._SL1200_.jpg",
        url: AMZ("/dp/B003R7YDME/"),
      },
    ],
  },
  {
    id: "vanity",
    eyebrow: "Collection 02",
    title: "The Vanity Ritual",
    subtitle: "Morning light. Marble. The ritual of your reflection.",
    hook: "Five minutes, before the day asks anything of you.",
    image:
      "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=900&q=80&auto=format&fit=crop",
    products: [
      {
        id: "marble-tray",
        brand: "Natural Stone",
        name: "Marble Vanity Tray",
        blurb: "The surface that holds everything and instantly upgrades every product on it.",
        rating: 4.8,
        reviews: 940,
        image: "https://m.media-amazon.com/images/I/41Y2J8cJnlL._SL1200_.jpg",
        url: AMZ("/dp/B0FG71XSSS/"),
      },
      {
        id: "rose-quartz-guasha",
        brand: "Plantifique",
        name: "Rose Quartz Gua Sha",
        blurb: "60 seconds of facial sculpting. The most-repurchased small object on this entire site.",
        rating: 4.6,
        reviews: 21400,
        badge: "Bestseller",
        image: "https://m.media-amazon.com/images/I/61a41EO4h6L._SL1200_.jpg",
        url: AMZ("/dp/B0B3RFS5KB/"),
      },
      {
        id: "jade-guasha",
        brand: "Plantifique",
        name: "Jade Gua Sha",
        blurb: "The ritual before anything else. Cool stone, warm face.",
        rating: 4.6,
        reviews: 21400,
        image: "https://m.media-amazon.com/images/I/71IqCJkSASL._SL1200_.jpg",
        url: AMZ("/dp/B0B3RJPM4L/"),
      },
      {
        id: "vitruvi-black",
        brand: "Vitruvi",
        name: "Stone Diffuser — Black Porcelain",
        blurb: "The scent architecture of the room, on a timer, so you never have to think about it again.",
        rating: 4.7,
        reviews: 12300,
        badge: "Editor's Pick",
        image: "https://m.media-amazon.com/images/I/71AzHZv8jtL._SL1200_.jpg",
        url: AMZ("/dp/B0CZ5DBL4Y/"),
      },
      {
        id: "louis-marie-oil",
        brand: "Maison Louis Marie",
        name: "No.04 Bois de Balincourt",
        blurb: "The signature. Applied before the world arrives.",
        size: "1.7 oz",
        rating: 4.8,
        reviews: 4870,
        image: "https://m.media-amazon.com/images/I/51Ou0JLiN1L._SL1200_.jpg",
        url: AMZ("/dp/B07JB273KY/"),
      },
      {
        id: "tatcha-dewy",
        brand: "Tatcha",
        name: "The Dewy Skin Cream",
        blurb: "The last step before the day begins. Cult status for a reason.",
        rating: 4.5,
        reviews: 3420,
        badge: "Trending",
        image: "https://m.media-amazon.com/images/I/51RFfDtchYL._SL1200_.jpg",
        url: AMZ("/dp/B09QBB8ZL4/"),
      },
    ],
  },
  {
    id: "ritual",
    eyebrow: "Collection 03",
    title: "The Ritual Hour",
    subtitle: "Scent, flame, stillness.",
    hook: "The hour before everything else — protected, on purpose.",
    image:
      "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=900&q=80&auto=format&fit=crop",
    products: [
      {
        id: "vitruvi-white",
        brand: "Vitruvi",
        name: "Stone Diffuser — White Porcelain",
        blurb: "The scent of the ritual hour, one wall outlet away.",
        rating: 4.7,
        reviews: 12300,
        image: "https://m.media-amazon.com/images/I/71u796LAwzL._SL1200_.jpg",
        url: AMZ("/dp/B0BCP1RG4B/"),
      },
      {
        id: "nest-3wick",
        brand: "NEST New York",
        name: "Bamboo 3-Wick Candle",
        blurb: "Bamboo & white tea. For the ritual that runs long.",
        size: "21.2 oz",
        rating: 4.8,
        reviews: 2960,
        image: "https://m.media-amazon.com/images/I/71o03YlbfnL._SL1200_.jpg",
        url: AMZ("/dp/B003U31MXS/"),
      },
      {
        id: "louis-marie-candle",
        brand: "Maison Louis Marie",
        name: "No.04 Candle",
        blurb: "Bois de balincourt. The hour of stillness in a jar.",
        size: "8.5 oz",
        rating: 4.8,
        reviews: 2140,
        badge: "Editor's Pick",
        image: "https://m.media-amazon.com/images/I/51ypg3QDH0L._SL1200_.jpg",
        url: AMZ("/dp/B07982DFFD/"),
      },
      {
        id: "margiela-jazz-club-candle",
        brand: "Maison Margiela",
        name: "REPLICA — Jazz Club Candle",
        blurb: "Tabac & vetiver. The room at the end of the evening.",
        size: "5.8 oz",
        rating: 4.6,
        reviews: 1680,
        image: "https://m.media-amazon.com/images/I/61JaRBLTg0L._SL1200_.jpg",
        url: AMZ("/dp/B075JMJ22X/"),
      },
      {
        id: "margiela-fireplace",
        brand: "Maison Margiela",
        name: "REPLICA — By the Fireplace",
        blurb: "Wood smoke & resin. Winter arrival, any season.",
        size: "1.0 oz",
        rating: 4.7,
        reviews: 1920,
        image: "https://m.media-amazon.com/images/I/71iel0T0rcL._SL1200_.jpg",
        url: AMZ("/dp/B08NZ4KR9T/"),
      },
      {
        id: "margiela-jazz-club",
        brand: "Maison Margiela",
        name: "REPLICA — Jazz Club",
        blurb: "The room before midnight.",
        size: "1.0 oz",
        rating: 4.7,
        reviews: 1610,
        image: "https://m.media-amazon.com/images/I/713JwZYtnsL._SL1200_.jpg",
        url: AMZ("/dp/B08R2CSXH1/"),
      },
    ],
  },
  {
    id: "journey",
    eyebrow: "Collection 04",
    title: "The Journey Kit",
    subtitle: "How she moves through the world. Quietly.",
    hook: "Everything you need fits in one beautiful bag.",
    image:
      "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=900&q=80&auto=format&fit=crop",
    products: [
      {
        id: "bellroy-passport",
        brand: "Bellroy",
        name: "Passport Cover",
        blurb: "Eco-tanned leather. Where the passport lives.",
        rating: 4.7,
        reviews: 3210,
        image: "https://m.media-amazon.com/images/I/51JgYNNM5dL._AC_SL1200_.jpg",
        url: AMZ("/dp/B0D4DKK8SD/"),
      },
      {
        id: "qavhun-atomizer",
        brand: "Qavhun",
        name: "Refillable Travel Atomizer (2-pack)",
        blurb: "The ritual, portable, TSA-approved.",
        size: "5 ml each",
        rating: 4.5,
        reviews: 9840,
        badge: "Bestseller",
        image: "https://m.media-amazon.com/images/I/710xxAEU3yL._SL1200_.jpg",
        url: AMZ("/dp/B0CJQ4LYT7/"),
      },
      {
        id: "mario-badescu-spray",
        brand: "Mario Badescu",
        name: "Facial Spray",
        blurb: "Rosewater & aloe. The mist she keeps in the outer pocket.",
        size: "4 oz",
        rating: 4.7,
        reviews: 47200,
        badge: "Cult Favorite",
        image: "https://m.media-amazon.com/images/I/61gkFcU2s7L._SL1200_.jpg",
        url: AMZ("/dp/B002LC9OES/"),
      },
      {
        id: "leuchtturm-notebook",
        brand: "Leuchtturm1917",
        name: "Pocket Notebook",
        blurb: "Hardcover. The record she keeps, wherever she is.",
        rating: 4.8,
        reviews: 5640,
        image: "https://m.media-amazon.com/images/I/51bKnKAHFyL._SL1200_.jpg",
        url: AMZ("/dp/B002CVAU1Y/"),
      },
      {
        id: "harney-sons-tea",
        brand: "Harney & Sons",
        name: "Classic Tea Sachets",
        blurb: "18 sachets. The quiet before departure, the lounge ritual.",
        rating: 4.8,
        reviews: 2870,
        image: "https://m.media-amazon.com/images/I/914s94Zq6BL._SL1200_.jpg",
        url: AMZ("/dp/B07NS9SDP4/"),
      },
    ],
  },
  {
    id: "details",
    eyebrow: "Collection 05",
    title: "The Small Details",
    subtitle: "The objects that change the register of a room.",
    hook: "Small spend, outsized effect. These are the objects guests actually notice.",
    image:
      "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=900&q=80&auto=format&fit=crop",
    products: [
      {
        id: "aesop-handwash",
        brand: "Aesop",
        name: "Reverence Aromatique Hand Wash",
        blurb: "The object that tells guests something about the room before they say a word.",
        rating: 4.8,
        reviews: 2310,
        image: "https://m.media-amazon.com/images/I/71T599oCmGL._SL1200_.jpg",
        url: AMZ("/dp/B00EJMQP3Q/"),
      },
      {
        id: "this-works-pillow-spray",
        brand: "This Works",
        name: "Deep Sleep Pillow Spray",
        blurb: "The scent before sleep — 89% of reviewers repurchase within a year.",
        size: "75 ml",
        rating: 4.7,
        reviews: 8920,
        badge: "Trending",
        image: "https://m.media-amazon.com/images/I/61po7Sj5YEL._SL1200_.jpg",
        url: AMZ("/dp/B006VT8G1O/"),
      },
      {
        id: "molton-brown-handwash",
        brand: "Molton Brown",
        name: "Orange & Bergamot Hand Wash",
        blurb: "The detail guests notice in the bathroom that says something.",
        size: "300 ml",
        rating: 4.7,
        reviews: 4120,
        image: "https://m.media-amazon.com/images/I/615D+ka6jPL._SL1200_.jpg",
        url: AMZ("/dp/B0BY37RD4C/"),
      },
      {
        id: "puskul-towels",
        brand: "Püskül",
        name: "Waffle Towel Set",
        blurb: "White. The texture of it — the first thing she touches.",
        rating: 4.6,
        reviews: 1980,
        image: "https://m.media-amazon.com/images/I/71MnQOCbTOL._AC_SL1500_.jpg",
        url: AMZ("/dp/B0BQBSY7PR/"),
      },
    ],
  },
]

export const allProducts: Product[] = collections.flatMap((c) => c.products)
