export interface Scent {
  id: string
  brand: string
  name: string
  blurb: string
  size: string
  gender: "men" | "women"
  price: number
  compareAt: number
  badge?: string
  image: string
  buyUrl: string
}

function savingsPct(price: number, compareAt: number) {
  return Math.round(((compareAt - price) / compareAt) * 100)
}

export const scents: Scent[] = [
  {
    id: "the-one",
    brand: "Dolce & Gabbana",
    name: "The One",
    blurb: "Zesty blood orange and warm woods. The bottle everyone asks to smell twice.",
    size: "3.4 oz Eau de Parfum",
    gender: "men",
    price: 70,
    compareAt: 123,
    badge: "Bestseller",
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/015e0efb-5ca0-4c97-8e37-9dfe933e4498.png",
    buyUrl: "https://buy.stripe.com/3cI28r14R80c7N16B58og0f",
  },
  {
    id: "wanted-by-night",
    brand: "Azzaro",
    name: "Wanted By Night",
    blurb: "Cinnamon, incense, and tobacco. Warm, spiced, unmistakably evening.",
    size: "3.4 oz Eau de Parfum",
    gender: "men",
    price: 79,
    compareAt: 125,
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/a97db5e9-9c52-4968-bbbe-933af164f310.png",
    buyUrl: "https://buy.stripe.com/cNi14n3cZ94gfft0cH8og0e",
  },
  {
    id: "1-million",
    brand: "Paco Rabanne",
    name: "1 Million",
    blurb: "Blood mandarin, cinnamon, leather. The gold bottle that started it all.",
    size: "3.4 oz Eau de Toilette",
    gender: "men",
    price: 85,
    compareAt: 122,
    badge: "Bestseller",
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/a72896a8-02a8-4856-bb8a-172a630d0391.png",
    buyUrl: "https://buy.stripe.com/5kQ9AT00N94gaZd8Jd8og0g",
  },
  {
    id: "hawas",
    brand: "Rasasi",
    name: "Hawas",
    blurb: "Cinnamon, orange blossom, sandalwood. The most-requested scent on this list.",
    size: "3.4 oz Eau de Parfum",
    gender: "men",
    price: 51,
    compareAt: 120,
    badge: "Best Value",
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/a97db5e9-9c52-4968-bbbe-933af164f310.png",
    buyUrl: "https://buy.stripe.com/9B6aEX14Rbco6IX3oT8og0h",
  },
  {
    id: "acqua-di-gio-profondo",
    brand: "Giorgio Armani",
    name: "Acqua Di Giò Profondo",
    blurb: "Marine, citrus, cedarwood. Clean and versatile — a daily signature.",
    size: "3.4 oz Eau de Toilette",
    gender: "men",
    price: 97,
    compareAt: 135,
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/fd43eeb2-f8a6-42bb-b015-0b8dc65d3beb.png",
    buyUrl: "https://buy.stripe.com/14A5kD3cZ94g8R5bVp8og0l",
  },
  {
    id: "eros",
    brand: "Versace",
    name: "Eros",
    blurb: "Mint, tonka bean, vanilla. Confident, warm, built to last all day.",
    size: "3.4 oz Eau de Parfum",
    gender: "men",
    price: 85,
    compareAt: 139,
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/fd43eeb2-f8a6-42bb-b015-0b8dc65d3beb.png",
    buyUrl: "https://buy.stripe.com/eVq6oHbJv94g8R5bVp8og0j",
  },
  {
    id: "boss-bottled",
    brand: "Hugo Boss",
    name: "Boss Bottled",
    blurb: "Apple, cinnamon, sandalwood. The office-to-dinner classic.",
    size: "3.4 oz Eau de Toilette",
    gender: "men",
    price: 66,
    compareAt: 127,
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/015e0efb-5ca0-4c97-8e37-9dfe933e4498.png",
    buyUrl: "https://buy.stripe.com/28E8wP7tf6W81oD0cH8og0k",
  },
  {
    id: "bleu-de-chanel",
    brand: "Chanel",
    name: "Bleu de Chanel",
    blurb: "Citrus, ginger, sandalwood. Understated, expensive, unforgettable.",
    size: "3.4 oz Eau de Parfum",
    gender: "men",
    price: 170,
    compareAt: 173,
    badge: "Prestige",
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/fd43eeb2-f8a6-42bb-b015-0b8dc65d3beb.png",
    buyUrl: "https://buy.stripe.com/dRm00jfZLeoAfftgbF8og0i",
  },
  {
    id: "la-vie-est-belle",
    brand: "Lancôme",
    name: "La Vie Est Belle",
    blurb: "Iris, patchouli, warm vanilla. Joyful, sweet, endlessly complimented.",
    size: "3.4 oz Eau de Parfum",
    gender: "women",
    price: 111,
    compareAt: 164,
    badge: "Bestseller",
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/1c3e9c2e-b2fc-415f-9e17-deda1073d877.png",
    buyUrl: "https://buy.stripe.com/14AdR95l7a8k0kz9Nh8og0o",
  },
  {
    id: "black-opium",
    brand: "Yves Saint Laurent",
    name: "Black Opium",
    blurb: "Coffee, vanilla, white flowers. Addictive, modern, unmistakable.",
    size: "3.0 oz Eau de Parfum",
    gender: "women",
    price: 124,
    compareAt: 172,
    badge: "Bestseller",
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/2b893ea1-95f8-4181-b7ba-108aa5eb68b0.png",
    buyUrl: "https://buy.stripe.com/bJe5kD28VgwIebpe3x8og0p",
  },
  {
    id: "good-girl",
    brand: "Carolina Herrera",
    name: "Good Girl",
    blurb: "Almond, tuberose, cacao. Bold, sweet, and a little dangerous.",
    size: "3.4 oz Eau de Parfum, Refillable",
    gender: "women",
    price: 130,
    compareAt: 180,
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/2b893ea1-95f8-4181-b7ba-108aa5eb68b0.png",
    buyUrl: "https://buy.stripe.com/dRmfZheVHfsE5ET3oT8og0n",
  },
  {
    id: "flowerbomb",
    brand: "Viktor&Rolf",
    name: "Flowerbomb",
    blurb: "Rose, peony, patchouli. A floral explosion in the best way.",
    size: "3.4 oz Eau de Parfum",
    gender: "women",
    price: 100,
    compareAt: 182,
    badge: "Best Value",
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/de915b54-ea35-4361-b5f9-65d8ace093d2.png",
    buyUrl: "https://buy.stripe.com/00weVd9Bn4O07N15x18og0m",
  },
  {
    id: "coco-mademoiselle",
    brand: "Chanel",
    name: "Coco Mademoiselle",
    blurb: "Orange, jasmine, patchouli. Timeless — the one that never goes out of style.",
    size: "3.4 oz Eau de Parfum",
    gender: "women",
    price: 178,
    compareAt: 185,
    badge: "Prestige",
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/2b893ea1-95f8-4181-b7ba-108aa5eb68b0.png",
    buyUrl: "https://buy.stripe.com/9B6eVdcNzdkw4AP2kP8og0q",
  },
  {
    id: "daisy",
    brand: "Marc Jacobs",
    name: "Daisy",
    blurb: "Wild berries, violet, jasmine. Light, radiant, effortlessly pretty.",
    size: "3.3 oz Eau de Toilette",
    gender: "women",
    price: 75,
    compareAt: 137,
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/de915b54-ea35-4361-b5f9-65d8ace093d2.png",
    buyUrl: "https://buy.stripe.com/dRm8wPdRDdkwc3haRl8og0r",
  },
  {
    id: "olympea",
    brand: "Paco Rabanne",
    name: "Olympéa",
    blurb: "Salty vanilla, pink pepper, cashmere wood. Modern, warm, magnetic.",
    size: "2.7 oz Eau de Parfum",
    gender: "women",
    price: 84,
    compareAt: 146,
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/5b7a2f36-2df3-42c7-89e7-c74b3b5ab66f.png",
    buyUrl: "https://buy.stripe.com/14A4gz3cZ5S4d7l4sX8og0t",
  },
  {
    id: "si",
    brand: "Giorgio Armani",
    name: "Sì",
    blurb: "Blackcurrant, rose, patchouli. Confident and modern, made for every day.",
    size: "3.4 oz Eau de Parfum",
    gender: "women",
    price: 103,
    compareAt: 115,
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/1c3e9c2e-b2fc-415f-9e17-deda1073d877.png",
    buyUrl: "https://buy.stripe.com/aFaeVd28Vcgs3wLf7B8og0s",
  },
]

export { savingsPct }
