export interface Scent {
  id: string
  brand: string
  name: string
  blurb: string
  size: string
  gender: "men" | "women"
  price: number
  compareAt: number
  badge?: string
  image: string
  /** Optional second authentic photo (box, alternate angle) used for hover-swap and gallery. */
  secondaryImage?: string
  /** True when `image` is a verified authentic product photo (not a placeholder render). */
  authentic?: boolean
  buyUrl: string
}

function savingsPct(price: number, compareAt: number) {
  return Math.round(((compareAt - price) / compareAt) * 100)
}

// Prices include free US shipping (built in, not charged separately).
//
// IMAGE SOURCING NOTE: 14 of 16 bottles below use verified authentic product
// photography (background-removed, matched by brand/bottle/cap/label against
// the source photo library). Two items — Hawas and Bleu de Chanel — could not
// be matched to a correct authentic photo in the current photo library (the
// only Hawas photos available were the "Elixir" and "For Her" flankers, and no
// Bleu de Chanel photo existed at all), so they remain on their prior
// placeholder image rather than risk showing the wrong bottle. Flagged with
// `authentic: false` — swap in a real photo as soon as one is sourced.
export const scents: Scent[] = [
  {
    id: "the-one",
    brand: "Dolce & Gabbana",
    name: "The One",
    blurb: "Zesty blood orange and warm woods. The bottle everyone asks to smell twice.",
    size: "3.4 oz Eau de Parfum",
    gender: "men",
    price: 75,
    compareAt: 123,
    badge: "Bestseller",
    image: "https://galaxy-prod.tlcdn.com/gen/user_3CP3WzpTXEewlb62LzPBeHUzEJS/ae3b04dd-5e9d-4e7c-ae92-2aa6ec342de3.png",
    secondaryImage: "https://galaxy-prod.tlcdn.com/gen/user_3CP3WzpTXEewlb62LzPBeHUzEJS/d7ad3f11-f241-4f72-a0c6-beb82b9d7cc3.webp",
    authentic: true,
    buyUrl: "https://buy.stripe.com/3cI3cvfZL2FSebp0cH8og0v",
  },
  {
    id: "wanted-by-night",
    brand: "Azzaro",
    name: "Wanted By Night",
    blurb: "Cinnamon, incense, and tobacco. Warm, spiced, unmistakably evening.",
    size: "3.4 oz Eau de Parfum",
    gender: "men",
    price: 84,
    compareAt: 125,
    image: "https://galaxy-prod.tlcdn.com/gen/user_3CP3WzpTXEewlb62LzPBeHUzEJS/bb22f488-8a94-4785-b8d9-9e9431dda2d8.png",
    secondaryImage: "https://galaxy-prod.tlcdn.com/gen/user_3CP3WzpTXEewlb62LzPBeHUzEJS/ddf92b8e-cebe-4646-bc1a-d1a519ec2c36.jpeg",
    authentic: true,
    buyUrl: "https://buy.stripe.com/7sY4gz5l7a8kfft2kP8og0x",
  },
  {
    id: "1-million",
    brand: "Paco Rabanne",
    name: "1 Million",
    blurb: "Blood mandarin, cinnamon, leather. The gold bottle that started it all.",
    size: "3.4 oz Eau de Toilette",
    gender: "men",
    price: 90,
    compareAt: 122,
    badge: "Bestseller",
    image: "https://galaxy-prod.tlcdn.com/gen/user_3CP3WzpTXEewlb62LzPBeHUzEJS/035c8d5f-6921-4901-8067-e443c28335bf.png",
    authentic: true,
    buyUrl: "https://buy.stripe.com/aFa4gz3cZ4O09V98Jd8og0w",
  },
  {
    id: "hawas",
    brand: "Rasasi",
    name: "Hawas",
    blurb: "Cinnamon, orange blossom, sandalwood. The most-requested scent on this list.",
    size: "3.4 oz Eau de Parfum",
    gender: "men",
    price: 56,
    compareAt: 120,
    badge: "Best Value",
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/a97db5e9-9c52-4968-bbbe-933af164f310.png",
    authentic: false,
    buyUrl: "https://buy.stripe.com/6oU8wP5l74O09V9e3x8og0u",
  },
  {
    id: "acqua-di-gio-profondo",
    brand: "Giorgio Armani",
    name: "Acqua Di Giò Profondo",
    blurb: "Marine, citrus, cedarwood. Clean and versatile — a daily signature.",
    size: "3.4 oz Eau de Toilette",
    gender: "men",
    price: 102,
    compareAt: 135,
    image: "https://galaxy-prod.tlcdn.com/gen/user_3CP3WzpTXEewlb62LzPBeHUzEJS/14916245-ad0f-490e-bc74-6f4000c618ef.png",
    secondaryImage: "https://galaxy-prod.tlcdn.com/gen/user_3CP3WzpTXEewlb62LzPBeHUzEJS/c52c549c-40bc-4f87-b2e4-929cb2db876b.jpeg",
    authentic: true,
    buyUrl: "https://buy.stripe.com/8x200jdRDdkw6IX8Jd8og0B",
  },
  {
    id: "eros",
    brand: "Versace",
    name: "Eros",
    blurb: "Mint, tonka bean, vanilla. Confident, warm, built to last all day.",
    size: "3.4 oz Eau de Parfum",
    gender: "men",
    price: 90,
    compareAt: 139,
    image: "https://galaxy-prod.tlcdn.com/gen/user_3CP3WzpTXEewlb62LzPBeHUzEJS/81684bd8-2cc1-412b-9494-6b356e044d4a.png",
    secondaryImage: "https://galaxy-prod.tlcdn.com/gen/user_3CP3WzpTXEewlb62LzPBeHUzEJS/b94169fd-3d03-4df2-97ac-6bca95e0b4d0.webp",
    authentic: true,
    buyUrl: "https://buy.stripe.com/4gM3cv3cZ94g9V90cH8og0A",
  },
  {
    id: "boss-bottled",
    brand: "Hugo Boss",
    name: "Boss Bottled",
    blurb: "Apple, cinnamon, sandalwood. The office-to-dinner classic.",
    size: "3.4 oz Eau de Toilette",
    gender: "men",
    price: 71,
    compareAt: 127,
    image: "https://galaxy-prod.tlcdn.com/gen/user_3CP3WzpTXEewlb62LzPBeHUzEJS/f6106474-8b90-4b27-888f-19571f927f1d.png",
    secondaryImage: "https://galaxy-prod.tlcdn.com/gen/user_3CP3WzpTXEewlb62LzPBeHUzEJS/6237fd02-a62e-4aff-a689-d8705891f560.webp",
    authentic: true,
    buyUrl: "https://buy.stripe.com/3cI9AT5l7a8k6IX8Jd8og0z",
  },
  {
    id: "bleu-de-chanel",
    brand: "Chanel",
    name: "Bleu de Chanel",
    blurb: "Citrus, ginger, sandalwood. Understated, expensive, unforgettable.",
    size: "3.4 oz Eau de Parfum",
    gender: "men",
    price: 175,
    compareAt: 185,
    badge: "Prestige",
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/fd43eeb2-f8a6-42bb-b015-0b8dc65d3beb.png",
    authentic: false,
    buyUrl: "https://buy.stripe.com/6oU5kDdRD94gc3hcZt8og0y",
  },
  {
    id: "la-vie-est-belle",
    brand: "Lancôme",
    name: "La Vie Est Belle",
    blurb: "Iris, patchouli, warm vanilla. Joyful, sweet, endlessly complimented.",
    size: "3.4 oz Eau de Parfum",
    gender: "women",
    price: 116,
    compareAt: 164,
    badge: "Bestseller",
    image: "https://galaxy-prod.tlcdn.com/gen/user_3CP3WzpTXEewlb62LzPBeHUzEJS/14dc3d3b-de5b-4c81-834e-ee90fa22a5d3.png",
    secondaryImage: "https://galaxy-prod.tlcdn.com/gen/user_3CP3WzpTXEewlb62LzPBeHUzEJS/5cd9e797-ac37-46c5-acab-66bf5700852a.jpeg",
    authentic: true,
    buyUrl: "https://buy.stripe.com/8x228rbJvgwI8R57F98og0C",
  },
  {
    id: "black-opium",
    brand: "Yves Saint Laurent",
    name: "Black Opium",
    blurb: "Coffee, vanilla, white flowers. Addictive, modern, unmistakable.",
    size: "3.0 oz Eau de Parfum",
    gender: "women",
    price: 129,
    compareAt: 172,
    badge: "Bestseller",
    image: "https://galaxy-prod.tlcdn.com/gen/user_3CP3WzpTXEewlb62LzPBeHUzEJS/3a47a0de-d04a-4434-b7c2-92e4decf3019.png",
    secondaryImage: "https://galaxy-prod.tlcdn.com/gen/user_3CP3WzpTXEewlb62LzPBeHUzEJS/15d9cc9b-1b38-4e93-8243-3cf73566dd61.webp",
    authentic: true,
    buyUrl: "https://buy.stripe.com/8x23cv28V4O0gjx0cH8og0E",
  },
  {
    id: "good-girl",
    brand: "Carolina Herrera",
    name: "Good Girl",
    blurb: "Almond, tuberose, cacao. Bold, sweet, and a little dangerous.",
    size: "3.4 oz Eau de Parfum, Refillable",
    gender: "women",
    price: 135,
    compareAt: 180,
    image: "https://galaxy-prod.tlcdn.com/gen/user_3CP3WzpTXEewlb62LzPBeHUzEJS/9137c6c8-d9e2-447e-acc6-9368aae61016.png",
    secondaryImage: "https://galaxy-prod.tlcdn.com/gen/user_3CP3WzpTXEewlb62LzPBeHUzEJS/2109e878-d277-4db8-9c8b-ccad0e9c8eb3.webp",
    authentic: true,
    buyUrl: "https://buy.stripe.com/bJedR99Bndkw7N1bVp8og0F",
  },
  {
    id: "flowerbomb",
    brand: "Viktor&Rolf",
    name: "Flowerbomb",
    blurb: "Rose, peony, patchouli. A floral explosion in the best way.",
    size: "3.4 oz Eau de Parfum",
    gender: "women",
    price: 105,
    compareAt: 182,
    badge: "Best Value",
    image: "https://galaxy-prod.tlcdn.com/gen/user_3CP3WzpTXEewlb62LzPBeHUzEJS/ca197608-4d6f-4f89-84d8-6cfa5a0db792.png",
    secondaryImage: "https://galaxy-prod.tlcdn.com/gen/user_3CP3WzpTXEewlb62LzPBeHUzEJS/33d39888-ae85-4dc6-8215-c03f84061f1d.webp",
    authentic: true,
    buyUrl: "https://buy.stripe.com/5kQ9ATbJv80c5ET4sX8og0D",
  },
  {
    id: "coco-mademoiselle",
    brand: "Chanel",
    name: "Coco Mademoiselle",
    blurb: "Orange, jasmine, patchouli. Timeless — the one that never goes out of style.",
    size: "3.4 oz Eau de Parfum",
    gender: "women",
    price: 183,
    compareAt: 192,
    badge: "Prestige",
    image: "https://galaxy-prod.tlcdn.com/gen/user_3CP3WzpTXEewlb62LzPBeHUzEJS/7a76e4f1-3296-4a91-a4f9-f97b6f1c263d.png",
    secondaryImage: "https://galaxy-prod.tlcdn.com/gen/user_3CP3WzpTXEewlb62LzPBeHUzEJS/15d9cc9b-1b38-4e93-8243-3cf73566dd61.webp",
    authentic: true,
    buyUrl: "https://buy.stripe.com/9B67sL6pbfsE0kz6B58og0G",
  },
  {
    id: "daisy",
    brand: "Marc Jacobs",
    name: "Daisy",
    blurb: "Wild berries, violet, jasmine. Light, radiant, effortlessly pretty.",
    size: "3.3 oz Eau de Toilette",
    gender: "women",
    price: 80,
    compareAt: 137,
    image: "https://galaxy-prod.tlcdn.com/gen/user_3CP3WzpTXEewlb62LzPBeHUzEJS/676cf07d-f299-4301-b9e9-da09a662ba99.png",
    secondaryImage: "https://galaxy-prod.tlcdn.com/gen/user_3CP3WzpTXEewlb62LzPBeHUzEJS/ac5e03fb-afb0-45fe-9063-2447e379d3da.webp",
    authentic: true,
    buyUrl: "https://buy.stripe.com/6oU9AT8xj6W83wL5x18og0I",
  },
  {
    id: "olympea",
    brand: "Paco Rabanne",
    name: "Olympéa",
    blurb: "Salty vanilla, pink pepper, cashmere wood. Modern, warm, magnetic.",
    size: "2.7 oz Eau de Parfum",
    gender: "women",
    price: 89,
    compareAt: 146,
    image: "https://galaxy-prod.tlcdn.com/gen/user_3CP3WzpTXEewlb62LzPBeHUzEJS/e6ce2f8a-ff01-4e82-a084-f79914042e1b.png",
    secondaryImage: "https://galaxy-prod.tlcdn.com/gen/user_3CP3WzpTXEewlb62LzPBeHUzEJS/17db1642-31fb-4ef9-8165-da9c8f15864c.jpeg",
    authentic: true,
    buyUrl: "https://buy.stripe.com/9B66oHbJva8kaZd9Nh8og0H",
  },
  {
    id: "si",
    brand: "Giorgio Armani",
    name: "Sì",
    blurb: "Blackcurrant, rose, patchouli. Confident and modern, made for every day.",
    size: "3.4 oz Eau de Parfum",
    gender: "women",
    price: 108,
    compareAt: 115,
    image: "https://galaxy-prod.tlcdn.com/gen/user_3CP3WzpTXEewlb62LzPBeHUzEJS/33fdbd37-a53d-4949-8ebc-1ce99969f144.png",
    secondaryImage: "https://galaxy-prod.tlcdn.com/gen/user_3CP3WzpTXEewlb62LzPBeHUzEJS/1eb776bf-bfee-41f4-89ca-61e8266e23c4.jpeg",
    authentic: true,
    buyUrl: "https://buy.stripe.com/3cI9AT7tf0xK3wLaRl8og0J",
  },
]

export { savingsPct }
