export interface Scent {
  id: string
  brand: string
  name: string
  blurb: string
  size: string
  gender: "men" | "women"
  price: number
  compareAt: number
  badge?: string
  image: string
  buyUrl: string
}

function savingsPct(price: number, compareAt: number) {
  return Math.round(((compareAt - price) / compareAt) * 100)
}

// Prices include free US shipping (built in, not charged separately).
export const scents: Scent[] = [
  {
    id: "the-one",
    brand: "Dolce & Gabbana",
    name: "The One",
    blurb: "Zesty blood orange and warm woods. The bottle everyone asks to smell twice.",
    size: "3.4 oz Eau de Parfum",
    gender: "men",
    price: 75,
    compareAt: 123,
    badge: "Bestseller",
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/015e0efb-5ca0-4c97-8e37-9dfe933e4498.png",
    buyUrl: "https://buy.stripe.com/3cI3cvfZL2FSebp0cH8og0v",
  },
  {
    id: "wanted-by-night",
    brand: "Azzaro",
    name: "Wanted By Night",
    blurb: "Cinnamon, incense, and tobacco. Warm, spiced, unmistakably evening.",
    size: "3.4 oz Eau de Parfum",
    gender: "men",
    price: 84,
    compareAt: 125,
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/a97db5e9-9c52-4968-bbbe-933af164f310.png",
    buyUrl: "https://buy.stripe.com/7sY4gz5l7a8kfft2kP8og0x",
  },
  {
    id: "1-million",
    brand: "Paco Rabanne",
    name: "1 Million",
    blurb: "Blood mandarin, cinnamon, leather. The gold bottle that started it all.",
    size: "3.4 oz Eau de Toilette",
    gender: "men",
    price: 90,
    compareAt: 122,
    badge: "Bestseller",
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/a72896a8-02a8-4856-bb8a-172a630d0391.png",
    buyUrl: "https://buy.stripe.com/aFa4gz3cZ4O09V98Jd8og0w",
  },
  {
    id: "hawas",
    brand: "Rasasi",
    name: "Hawas",
    blurb: "Cinnamon, orange blossom, sandalwood. The most-requested scent on this list.",
    size: "3.4 oz Eau de Parfum",
    gender: "men",
    price: 56,
    compareAt: 120,
    badge: "Best Value",
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/a97db5e9-9c52-4968-bbbe-933af164f310.png",
    buyUrl: "https://buy.stripe.com/6oU8wP5l74O09V9e3x8og0u",
  },
  {
    id: "acqua-di-gio-profondo",
    brand: "Giorgio Armani",
    name: "Acqua Di Giò Profondo",
    blurb: "Marine, citrus, cedarwood. Clean and versatile — a daily signature.",
    size: "3.4 oz Eau de Toilette",
    gender: "men",
    price: 102,
    compareAt: 135,
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/fd43eeb2-f8a6-42bb-b015-0b8dc65d3beb.png",
    buyUrl: "https://buy.stripe.com/8x200jdRDdkw6IX8Jd8og0B",
  },
  {
    id: "eros",
    brand: "Versace",
    name: "Eros",
    blurb: "Mint, tonka bean, vanilla. Confident, warm, built to last all day.",
    size: "3.4 oz Eau de Parfum",
    gender: "men",
    price: 90,
    compareAt: 139,
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/fd43eeb2-f8a6-42bb-b015-0b8dc65d3beb.png",
    buyUrl: "https://buy.stripe.com/4gM3cv3cZ94g9V90cH8og0A",
  },
  {
    id: "boss-bottled",
    brand: "Hugo Boss",
    name: "Boss Bottled",
    blurb: "Apple, cinnamon, sandalwood. The office-to-dinner classic.",
    size: "3.4 oz Eau de Toilette",
    gender: "men",
    price: 71,
    compareAt: 127,
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/015e0efb-5ca0-4c97-8e37-9dfe933e4498.png",
    buyUrl: "https://buy.stripe.com/3cI9AT5l7a8k6IX8Jd8og0z",
  },
  {
    id: "bleu-de-chanel",
    brand: "Chanel",
    name: "Bleu de Chanel",
    blurb: "Citrus, ginger, sandalwood. Understated, expensive, unforgettable.",
    size: "3.4 oz Eau de Parfum",
    gender: "men",
    price: 175,
    compareAt: 185,
    badge: "Prestige",
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/fd43eeb2-f8a6-42bb-b015-0b8dc65d3beb.png",
    buyUrl: "https://buy.stripe.com/6oU5kDdRD94gc3hcZt8og0y",
  },
  {
    id: "la-vie-est-belle",
    brand: "Lancôme",
    name: "La Vie Est Belle",
    blurb: "Iris, patchouli, warm vanilla. Joyful, sweet, endlessly complimented.",
    size: "3.4 oz Eau de Parfum",
    gender: "women",
    price: 116,
    compareAt: 164,
    badge: "Bestseller",
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/1c3e9c2e-b2fc-415f-9e17-deda1073d877.png",
    buyUrl: "https://buy.stripe.com/8x228rbJvgwI8R57F98og0C",
  },
  {
    id: "black-opium",
    brand: "Yves Saint Laurent",
    name: "Black Opium",
    blurb: "Coffee, vanilla, white flowers. Addictive, modern, unmistakable.",
    size: "3.0 oz Eau de Parfum",
    gender: "women",
    price: 129,
    compareAt: 172,
    badge: "Bestseller",
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/2b893ea1-95f8-4181-b7ba-108aa5eb68b0.png",
    buyUrl: "https://buy.stripe.com/8x23cv28V4O0gjx0cH8og0E",
  },
  {
    id: "good-girl",
    brand: "Carolina Herrera",
    name: "Good Girl",
    blurb: "Almond, tuberose, cacao. Bold, sweet, and a little dangerous.",
    size: "3.4 oz Eau de Parfum, Refillable",
    gender: "women",
    price: 135,
    compareAt: 180,
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/2b893ea1-95f8-4181-b7ba-108aa5eb68b0.png",
    buyUrl: "https://buy.stripe.com/bJedR99Bndkw7N1bVp8og0F",
  },
  {
    id: "flowerbomb",
    brand: "Viktor&Rolf",
    name: "Flowerbomb",
    blurb: "Rose, peony, patchouli. A floral explosion in the best way.",
    size: "3.4 oz Eau de Parfum",
    gender: "women",
    price: 105,
    compareAt: 182,
    badge: "Best Value",
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/de915b54-ea35-4361-b5f9-65d8ace093d2.png",
    buyUrl: "https://buy.stripe.com/5kQ9ATbJv80c5ET4sX8og0D",
  },
  {
    id: "coco-mademoiselle",
    brand: "Chanel",
    name: "Coco Mademoiselle",
    blurb: "Orange, jasmine, patchouli. Timeless — the one that never goes out of style.",
    size: "3.4 oz Eau de Parfum",
    gender: "women",
    price: 183,
    compareAt: 192,
    badge: "Prestige",
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/2b893ea1-95f8-4181-b7ba-108aa5eb68b0.png",
    buyUrl: "https://buy.stripe.com/9B67sL6pbfsE0kz6B58og0G",
  },
  {
    id: "daisy",
    brand: "Marc Jacobs",
    name: "Daisy",
    blurb: "Wild berries, violet, jasmine. Light, radiant, effortlessly pretty.",
    size: "3.3 oz Eau de Toilette",
    gender: "women",
    price: 80,
    compareAt: 137,
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/de915b54-ea35-4361-b5f9-65d8ace093d2.png",
    buyUrl: "https://buy.stripe.com/6oU9AT8xj6W83wL5x18og0I",
  },
  {
    id: "olympea",
    brand: "Paco Rabanne",
    name: "Olympéa",
    blurb: "Salty vanilla, pink pepper, cashmere wood. Modern, warm, magnetic.",
    size: "2.7 oz Eau de Parfum",
    gender: "women",
    price: 89,
    compareAt: 146,
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/5b7a2f36-2df3-42c7-89e7-c74b3b5ab66f.png",
    buyUrl: "https://buy.stripe.com/9B66oHbJva8kaZd9Nh8og0H",
  },
  {
    id: "si",
    brand: "Giorgio Armani",
    name: "Sì",
    blurb: "Blackcurrant, rose, patchouli. Confident and modern, made for every day.",
    size: "3.4 oz Eau de Parfum",
    gender: "women",
    price: 108,
    compareAt: 115,
    image: "https://galaxy-prod.tlcdn.com/gen/user_32yYblHkbisLQe7Nwwn2NH6XK4h/1c3e9c2e-b2fc-415f-9e17-deda1073d877.png",
    buyUrl: "https://buy.stripe.com/3cI9AT7tf0xK3wLaRl8og0J",
  },
]

export { savingsPct }
